name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytest
  - flake8
  - black
  - isort
  - tornado
  - toolz
  - zict
  - six
  - librdkafka=1.2.2
  - dask
  - distributed
  - pandas
  - python-confluent-kafka=1.5.0
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - codecov
  - coverage
  - networkx
  - graphviz
  - python-graphviz
  - pytest-asyncio
  - bokeh
  - ipython
  - ipykernel
  - ipywidgets
  - flaky
  - pytest-cov
  - coveralls
  - paho-mqtt
  - websockets
